### ISSUE TITLE
NullpointerException  Issue

### ISSUE THREAD

**Issue by aaryan1** [jrummyapps/colorpicker#11]
Getting  null  pointer exception  when selecting the color  like  this--
java.lang.NullPointerException: Attempt to invoke interface method 'void com.jrummyapps.android.colorpicker.ColorPickerDialogListener.onColorSelected(int, int)' on a null object reference
                                                                              at com.jrummyapps.android.colorpicker.ColorPickerDialog$1.onClick(ColorPickerDialog.java:172)

**Comment by jaredrummler** [comment]
Does your activity implement `ColorPickerDialogListener` or did you set a listener when creating the dialog using `setColorPickerDialogListener`?

**Comment by aaryan1** [comment]
Actually  i am working  with  fragment -- here is the cod---------------
import android.app.Activity;
import android.content.Context;
import android.graphics.Color;
import android.graphics.Point;
import android.os.Bundle;
import android.support.annotation.ColorInt;
import android.support.annotation.Nullable;
import android.support.v7.app.AlertDialog;
import android.view.Display;
import android.view.View;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.GridView;

import com.app2mobile.Sultanwok.CustomizeActivity;
import com.app2mobile.Sultanwok.R;
import com.jrummyapps.android.colorpicker.ColorPickerDialog;
import com.jrummyapps.android.colorpicker.ColorPickerDialogListener;

public class CustomizeFragment extends  BaseFragment implements android.support.v4.app.FragmentManager.OnBackStackChangedListener, ColorPickerDialogListener {

    Button colorpicker;
    private Context mContext;
    private int mPickedColor = Color.WHITE;
             public static CustomizeFragment newInstance() {

                               return new CustomizeFragment();}

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mContext = getContext();
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mTitleTxt.setText("Customize");
        mCartImg.setVisibility(View.INVISIBLE);
        mCartCountTxt.setVisibility(View.INVISIBLE);
        circle.setVisibility(View.INVISIBLE);
        mEditImg.setVisibility(View.INVISIBLE);

          colorpicker = (Button)view.findViewById(R.id.colorpicker);
        colorpicker.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                ColorPickerDialog.newBuilder()
                        .setAllowPresets(true)
                        .setColor(Color.BLACK).setDialogId(0)
                        .setShowAlphaSlider(true)
                        .show(getActivity());


            }
        });
    }

    @Override
    public int getLayout() {
        return R.layout.fragment_customize;
    }

    @Override
    public void onBackStackChanged() {
        // TODO Auto-generated method stub
        int backStackEntryCount = getFragmentManager().getBackStackEntryCount();
        if(backStackEntryCount > 0){
            getActivity().getActionBar().setDisplayHomeAsUpEnabled(true);
        }else{
            getActivity().getActionBar().setDisplayHomeAsUpEnabled(false);
        }
    }

    @Override
    public void onColorSelected(int dialogId, @ColorInt int color)
    {
               if(dialogId==0) {
                   colorpicker.setBackgroundColor(color);
               }

    }

    @Override
    public void onDialogDismissed(int dialogId) {

    }
}

**Comment by aaryan1** [comment]
i solved it  thanks  for your  kind help;

**Comment by natiq266** [comment]
how did you solve it? please post answer here to help others as i am getting same issue with same situation

**Comment by callingmedic911** [comment]
ColorPickerDialogListener should be implemented in containing Activity instead of Fragment.

This might help someone having similar issue.
