### ISSUE TITLE
Feature - select stroke width

### ISSUE THREAD

**Issue by bizzguy** [jrummyapps/colorpicker#17]
I've got a drawing app where the user can select color, alpha and stroke width.  It would be useful to have this library also allow the user to select stroke width (and maybe show a dot next to the selection to show how big the stroke would be).  This should be a feature, like alpha, that can be turned on or off.

**Comment by jaredrummler** [comment]
While that would be a nice feature, I think it is beyond the scope of the project. If you send a PR I might accept it. Thanks.
