### ISSUE TITLE
How can I use this in Fragment? 

### ISSUE THREAD

**Issue by sachinrana135** [jrummyapps/colorpicker#19]
How can I use this in Fragment?  I have added listener in parent activity  of fragment and its working but I want to listen **onColorSelected** in fragment. 
Please help.

**Comment by jaredrummler** [comment]
See #5

**Comment by sachinrana135** [comment]
Thank for reply.

I have just looked into that but that will be fine for only one fragment. What If I am selecting color from multiple fragments then how do I know which fragment listener I need to call?

**Comment by sachinrana135** [comment]
I can do that using conditions of fragment color picker DIALOG_ID in parent activity. Right?

**Comment by jaredrummler** [comment]
You will need a way to get the current fragment. Are the fragments in a ViewPager? You can also use an event bus.

**Comment by sachinrana135** [comment]
I have an activity containing two fragments. Both the fragments can open color picker dialog. Now I just need to listen the **onColorSelected** on the same fragment from where it is invoked. One way to have different DIALOG_ID in both fragments and will get DIALOG_ID in **onColorSelected** listener in parent activity. After that, according to DIALOG_ID, I can call the  **onColorSelected** of target fragment activity.

Is this the right way or any suggestion?

Thanks
