### ISSUE TITLE
Separating the dialog callback interface

### ISSUE THREAD

**Issue by sazid** [jrummyapps/colorpicker#4]
Can't the dialog callback interface be separated from the activity such that I can supply my own implementation of the `ColorPickerDialogListener` independent of the activity I'm using it in? Maybe something like this:
`ColorPickerDialog.newBuilder().setColor(color).show(Activity);` can be changed to `ColorPickerDialog.newBuilder().setColor(color).show(Activity, ColorPickerDialogListener);`

**Comment by jaredrummler** [comment]
Yes, you can already do this. Example:

```java
ColorPickerDialog dialog = ColorPickerDialog.newBuilder().setColor(Color.RED).create();
dialog.setColorPickerDialogListener(new ColorPickerDialogListener() {
  @Override public void onColorSelected(int dialogId, @ColorInt int color) {
    // do something
  }

  @Override public void onDialogDismissed(int dialogId) {
    // do something
  }
});
dialog.show(getFragmentManager(), "ColorPickerDialog");
```

If you are using `ColorPreference` then you shouldn't have to worry about the callback.

**Comment by sazid** [comment]
Thanks :D and sorry for not checking it out thoroughly. I think you should document this code in the README too :)
