### ISSUE TITLE
Conflicting style attribute with Preference Support Library

### ISSUE THREAD

**Issue by mtthsfrdrch** [jrummyapps/colorpicker#7]
When trying to use the lib while also using the Preference Support Library the build results in a conflict. 
> Error:(1000) Attribute "dialogTitle" already defined with incompatible format.

You can easily test this by adding the preference support lib to the dependencies of the demo app:
`compile "com.android.support:preference-v14:25.1.0"`

To solve this i think it would be good to prefix the custom style attributes defined by this library.

**Comment by jaredrummler** [comment]
c9578165cb1170bec3d4c53fff5ee05b9d78b47fa
